### ISSUE TITLE
fix the rss feed to export more tags

### ISSUE THREAD

**Issue by Badtz13** [PSCS-Coding/stickers#11]
for some reason every class is now facilitated by nic. I am unsure why. It would be great if the rss feed put out block as well.

**Comment by nwarmenh** [comment]
Sorry, I'm not likely to work on this.  I thin one of you would do well to learn how to make [custom wordpress feeds](https://codex.wordpress.org/Customizing_Feeds).  Perhaps a good job for @Appleguy15 , as the resident Wordpress jock?
