### ISSUE TITLE
create stickers.pscs.org

### ISSUE THREAD

**Issue by Badtz13** [PSCS-Coding/stickers#18]
i am working on writing the stickers app and it would be _very_ helpful to have a server to set up ajax requests to. @eastonkugler

**Comment by nwarmenh** [comment]
I have just created the subdomain record on bluehost (which has created a /stickers directory where all the files will go).

I have also a request to Paul to add stickers.pscs.org to the zone file for the domain.  I don't know whether this will work, given that Bluehost is already just hosting a subdomain, but we'll see.

It will take some time for Paul to see my request and do the work, and then some time for the DNS change to propagate.

**Comment by Badtz13** [comment]
alright, thanks

**Comment by nwarmenh** [comment]
Done.
