### ISSUE TITLE
the label for what type of sorting is happening is behind the remaining stickers

### ISSUE THREAD

**Issue by Badtz13** [PSCS-Coding/stickers#35]
![river fix](https://cloud.githubusercontent.com/assets/6172936/9503187/5157f238-4bea-11e5-9df0-f915a36a56f7.PNG)
the white text behind there is supposed to be below the remaining stickers.

**Comment by ghost** [comment]
oh sheet i feex now :100:

**Comment by ghost** [comment]
I'm not seeing any white text behind the stickers on my computer?

![screen shot 2015-08-26 at 1 36 36 pm](https://cloud.githubusercontent.com/assets/10405269/9505464/82241e52-4bf7-11e5-8e2c-0a293f10ddad.png)

**Comment by Badtz13** [comment]
click on one of the table headers, like the part that says category.

**Comment by ghost** [comment]
you want it below the remaining?

**Comment by Badtz13** [comment]
yeee

**Comment by ghost** [comment]
#39 
![screen shot 2015-08-26 at 1 48 33 pm](https://cloud.githubusercontent.com/assets/10405269/9505774/2978fd16-4bf9-11e5-8810-9a48b85dfbe4.png)
