### ISSUE TITLE
make not horrible css

### ISSUE THREAD

**Issue by Badtz13** [PSCS-Coding/stickers#6]
right now i made temp css for stuff, please make it not so bad @riverehill

**Comment by eastonkugler** [comment]
http://i.imgur.com/c7qCvxq.png

**Comment by riverehill** [comment]
😜😜👅💸💸👌🏿👌🏿🍼😍

**Comment by eastonkugler** [comment]
on it

**Comment by eastonkugler** [comment]
I'd say its gud now
