### ISSUE TITLE
create student page

### ISSUE THREAD

**Issue by Badtz13** [PSCS-Coding/stickers#8]
i have already created a student.php page that lets you choose between all the students for login, but it would be great to show what classes each student had stickered on this page as well. Maybe some other information would be good for here as well such as remaining stickers and stuff.

**Comment by rabu870** [comment]
I don't know how to use SQL...

**Comment by Badtz13** [comment]
you will need @eastonkugler  to help you set up xamp or lamp on your laptop and install mysql. once you do that, we can help you get started. Here's a link to some basic information about mysql php queries. http://php.net/manual/en/function.mysql-query.php

**Comment by Badtz13** [comment]
also, if you get skype, tell me and @eastonkugler  your account name and @eastonkugler  can help you get set up later tonight.

**Comment by rabu870** [comment]
I got lamp, but I didn't get MySql.
@eastonkugler will hopefully help me tomorrow.
Thanks

**Comment by rabu870** [comment]
Also, do you want me to use PHP or Javascript for the select person...?
And do you pull the students (that you select) from a database?

**Comment by elikimchi** [comment]
thank you

**Comment by rabu870** [comment]
Dang it! the age limit for skype is 13. We could use google video chat though...?
